# fly.toml app configuration file generated for trackermax on 2023-08-29T14:09:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trackermax"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
